In [1]:
import numpy as np

mylist =[1,3,4, 5]
array = np.array(mylist)

print(array)

[1 3 4 5]


In [2]:
import numpy as np

# Create a NumPy array with values from 1 to 10
my_array = np.arange(1, 11)
print(my_array)

[ 1  2  3  4  5  6  7  8  9 10]


In [3]:
random_matrix = np.random.randint(low=1, high=100, size=(3, 3))
print(random_matrix)

[[39 65 97]
 [59 28 36]
 [39 61 30]]


In [4]:
random_matrix = np.random.rand(3, 3)
print(random_matrix)
print(type(random_matrix))

[[0.02494215 0.94140863 0.7570292 ]
 [0.66914056 0.53704592 0.75784285]
 [0.6690785  0.7563469  0.0606661 ]]
<class 'numpy.ndarray'>


In [5]:
alist = [[1,2,4], [34, 43, 67]]
array2 = np.array(alist)

In [6]:
array = [[94,67,4], [77, 45, 77]]
addition = array +array2
print(addition)

[[ 95  69   8]
 [111  88 144]]


In [7]:
subtract = array -array2
print(subtract)

[[93 65  0]
 [43  2 10]]


In [8]:
multiply = array * array2
print(multiply)

[[  94  134   16]
 [2618 1935 5159]]


In [11]:
division_result = np.divide(array, array2, out=np.zeros_like(array), where=array2 != 0)
print(division_result)

UFuncTypeError: Cannot cast ufunc 'divide' output from dtype('float64') to dtype('int32') with casting rule 'same_kind'

# Array Creation

#    1. Using Lists or Tuples:

In [6]:
import numpy as np

# Create an array from a list
arr_list = np.array([1, 2, 3, 4, 5])
print("list array = ",arr_list)

# Create an array from a tuple
arr_tuple = np.array((1, 2, 3, 4, 5))
print("tupple array = ",arr_tuple)

list array =  [1 2 3 4 5]
tupple array =  [1 2 3 4 5]


#    2. Using Special Functions

In [11]:
# Create an array filled with zeros
zeros_array = np.zeros((3, 3))
print("zeros array = \n",zeros_array,"\n")

# Create an array filled with ones
ones_array = np.ones((2, 4))
print("ones array = \n",ones_array,"\n")

# Create an array filled with a specified value
full_array = np.full((2, 3), 5)
print("full array = \n",full_array,"\n")

# Create an array with evenly spaced values within a given interval
arange_array = np.arange(0, 10, 2)
print("evenly spaced array within given interval = \n",arange_array,"\n")

# Create an array with evenly spaced values over a specified range
linspace_array = np.linspace(0, 10, 5)
print("evenly spaced aray over a specified range = \n",linspace_array,"\n")

# Create an array of random values between 0 and 1
rand_array = np.random.rand(2, 3)
print("random array = \n",rand_array,"\n")

# Create an array of random integers within a specified range
randint_array = np.random.randint(1, 10, size=(2, 3))
print("array of random integers within a specified range = \n",randint_array,"\n")

# Create a 2-D array with ones on the diagonal and zeros elsewhere (identity matrix)
eye_array = np.eye(3)
print("identity matrix = \n", eye_array,"\n")


zeros array = 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

ones array = 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]] 

full array = 
 [[5 5 5]
 [5 5 5]] 

evenly spaced array within given interval = 
 [0 2 4 6 8] 

evenly spaced aray over a specified range = 
 [ 0.   2.5  5.   7.5 10. ] 

random array = 
 [[0.66800103 0.0120733  0.42631941]
 [0.45699696 0.94179935 0.6441463 ]] 

array of random integers within a specified range = 
 [[8 9 2]
 [7 5 2]] 

identity matrix = 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 



# Indexing and Slicing:"

In [14]:
# Indexing
print("Indexing ",arr_list[0])  # Output: 1

# Slicing
print("Slicing ",arr_list[1:4])  # Output: [2 3 4]

Indexing  1
Slicing  [2 3 4]


# Reshaping and Resizing:

In [20]:
#Original array
print("Original array = \n",arr_list, "\n" )

# Reshape an array
reshaped_array = np.reshape(arr_list, (5, 1))
print("Reshaped array = \n",reshaped_array, "\n" )

# Resize an array
resized_array = np.resize(arr_list, (3, 3))
print("Resized array = \n",resized_array, "\n" )

# Flatten an array
flattened_array = arr_list.ravel()
print("Flattened array = \n",flattened_array, "\n" )


Original array = 
 [1 2 3 4 5] 

Reshaped array = 
 [[1]
 [2]
 [3]
 [4]
 [5]] 

Resized array = 
 [[1 2 3]
 [4 5 1]
 [2 3 4]] 

Flattened array = 
 [1 2 3 4 5] 



# Stacking and Splitting:

In [21]:
# Concatenate arrays
concatenated_array = np.concatenate((arr_list, arr_tuple))
print("Concatenated array = \n",concatenated_array, "\n" )

# Stack arrays vertically
vstack_array = np.vstack((arr_list, arr_tuple))
print("vertically stacked array = \n",vstack_array, "\n" )


# Stack arrays horizontally
hstack_array = np.hstack((arr_list, arr_tuple))
print("horizontally stacked array = \n",hstack_array, "\n" )


# Split an array into multiple sub-arrays
splitted_array = np.split(arr_list, 2)
print("Splitted sub array = \n",splitted_array, "\n" )



Concatenated array = 
 [1 2 3 4 5 1 2 3 4 5] 

vertically stacked array = 
 [[1 2 3 4 5]
 [1 2 3 4 5]] 

horizontally stacked array = 
 [1 2 3 4 5 1 2 3 4 5] 



ValueError: array split does not result in an equal division

# Adding and Removing Elements:

In [23]:
# Append values to the end of an array
appended_array = np.append(arr_list, 6)
print("Appended array = \n",appended_array, "\n" )

# Insert values into an array
inserted_array = np.insert(arr_list, 2, 10)
print("inserted array = \n",inserted_array, "\n" )


# Delete elements from an array
deleted_array = np.delete(arr_list, 3)
print("deleted array = \n",deleted_array, "\n" )


Appended array = 
 [1 2 3 4 5 6] 

inserted array = 
 [ 1  2 10  3  4  5] 

deleted array = 
 [1 2 3 5] 



# Transposing and Flipping:

In [24]:
# Transpose an array
transposed_array = np.transpose(resized_array)
print("transposed array = \n",transposed_array, "\n" )

# Reverse the order of elements in an array along a specified axis
flipped_array = np.flip(arr_list)
print("flipped array = \n",flipped_array, "\n" )

transposed array = 
 [[1 4 2]
 [2 5 3]
 [3 1 4]] 

flipped array = 
 [5 4 3 2 1] 



# Transposing and Flipping:

In [27]:
# Return a sorted copy of an array
sorted_array = np.sort(arr_list)
print("sorted array = \n",sorted_array, "\n" )

# Return the indices that would sort an array
sorted_indices = np.argsort(arr_list)
print("sorted indices = \n",sorted_indices, "\n" )

# Find the indices where elements should be inserted to maintain order
search_indices = np.searchsorted(arr_list, 3)
print("elements should be inserted to maintain order = ",search_indices )

sorted array = 
 [1 2 3 4 5] 

sorted indices = 
 [0 1 2 3 4] 

elements should be inserted to maintain order =  2
